var country = new Array();
country["Abkhazie"] = new Array("Aquafon");
country["Afghanistan"] = new Array("Areeba (MTN Afghanistan)",
    "AWCC (Afghan Wireless Communication Company)",
    "Etisalat Afghanistan",
    "ROSHAN (TDCA Ltd)");
country["Afrique du Sud"] = new Array("8.ta (Telkom Mobile)",
    "Cell C",
    "MTN",
    "MTN Special",
    "Vodacom");
country["Albanie"] = new Array("AMC (Albania Mobile Communications)",
    "Eagle Mobile",
    "Plus",
    "Vodafone Albania");
country["Algerie"] = new Array("Djezzy (Orascom Telecom Algerie)",
    "Mobilis (ATM Mobilis)",
    "Nedjma (Watanlya Telecom Algerie)");
country["Allemagne"] = new Array("E-Plus",
    "Ring Mobilfunk (E-Plus MVNO)",
    "T-Mobile (Deutsche Telekom)",
    "Telefonica O2 Germany",
    "ViStream (E-Plus MVNE)",
    "Vodafone D2");
country["Andorre"] = new Array("Mobiland (Andorra Telecom)");
country["Angola"] = new Array("Movicel (CDMA)", "UNITEL");
country["Anguilla"] = new Array("Cable & Wireless (Wiest Indies) Anguilla",
   "Digicel Anguilla",
   "Weblinks Mobile");
country["Antigua et Barbuda"] = new Array("APUA PCS (Antigua Public Utilities Authority)",
    "Digicel Antigua and Barbuda");
country["Arabie Saoudite"] = new Array("Mobily (Etihad Etisalat Company)",
    "STC (Saudi Telecom Company)",
    "Zain SA (MTC Saudi Arabia)");
country["Argentine"] = new Array("Claro Argentina (AMX Argentina S.A.) (fka CTI Movil)",
    "Movistar (Telefonica Moviles Argentina S.A.)",
    "Nextel (NII Holdings Inc)",
    "Telecom Personal S.A.");
country["Arménie"] = new Array("Beeline (ArmenTel)",
    "Karabagh Telecom",
    "Orange Armenia",
    "VivaCell-MTS (K Telecom CJSC)");
country["Aruba"] = new Array("Digicel Aruba (New Millenium Telecom Services (NMTS))",
    "SETAR N.V. (Servicio di Telecomunicacion di Aruba)");
country["Australie"] = new Array("Hutchison 3G Australia",
    "Telstra",
    "Vodafone Australia",
    "YES OPTUS (Singtel Optus Ltd)");
country["Autriche"] = new Array("3 AT (Hutchison 3G Austria)",
    "A1 (Mobilkom Austria)",
    "Orange Austria (fka One)",
    "T-Mobile Austria",
    "tele.ring (T-Mobile Austria)",
    "Tele2 Austria (Orange MVNO)");
country["Azerbaïjan"] = new Array("Azercell",
    "Bakcell",
    "Nar Mobile (Azerfon LLC)");
country["Bahamas"] = new Array("BaTelCo (BTC)");
country["Bahreïn"] = new Array("Batelco (Bahrain Telecommunications Company)",
    "VIVA Bahrain (STC)",
    "Zain BH (fka. MTC Vodafone)");
country["Bangladesh"] = new Array("Airtel Bangladesh (fka Warid)",
    "Banglalink (Orascom Telecom Holding)",
    "Grameenphone",
    "Robi (Axiata Bangladesh Ltd)",
    "TeleTalk");
country["Barbade"] = new Array("Digicel Barbados",
    "LIME (Cable %26 Wireless)");
country["Belarus"] = new Array("life:) (Belarusian Telecommunications Network CJSC)",
    "MTS (JLLC Mobile TeleSystems)",
    "velcom");
country["Belgique"] = new Array("KPN Group Belgium NV/SA (fka Base)",
    "Mobistar S.A.",
    "Proximus (Belgacom SA/NV)");
country["Belize"] = new Array("Belize Telecommunications (Belize Telemedia Limited)");
country["Benin"] = new Array("GloBenin (Glomobile Benin Ltd)",
    "Libercom (Benin Telecoms Mobile)",
    "Moov Benin (Etisalat Benin S.A.)",
    "MTN Benin (Spacetel)");
country["Bermudes"] = new Array("Digicel Bermuda (Telecommunications (Bermuda %26 West Indies) Ltd)",
    "Mobility (M3 Wireless)");
country["Bhoutan"] = new Array("B-Mobile");
country["Bolivie"] = new Array("Entel",
    "Nuevatel PCS De Bolivia",
    "Tigo (Telecel Bolivia)");
country["Bosnie-Herzégovine"] = new Array("BH Mobile (BH Telecom)",
    "HT-ERONET",
    "m:tel (Telekom Srpske JSC Banjaluka)");
country["Botswana"] = new Array("BTC Mobile (Botswana Telecommunications Corporation)",
    "Mascom Wireless",
    "Orange Botswana");
country["Brésil"] = new Array("aeiou (Unicel do Brasil) / SP Sao Paulo",
    "Claro (Americel S.A.) / AC Rio Branco",
    "Claro (Americel S.A.) / DF Brasilia",
    "Claro (Americel S.A.) / GO Goiania",
    "Claro (Americel S.A.) / MS Campo Grande",
    "Claro (Americel S.A.) / MT Cuiaba",
    "Claro (Americel S.A.) / RO Porto Velho",
    "Claro (Americel S.A.) / TO Palmas",
    "Claro (CLARO S.A.) / AL Maceio",
    "Claro (CLARO S.A.) / AM Manaus",
    "Claro (CLARO S.A.) / AP Macapa",
    "Claro (CLARO S.A.) / BA Salvador",
    "Claro (CLARO S.A.) / CE Fortaleza",
    "Claro (CLARO S.A.) / DF Brasilia",
    "Claro (CLARO S.A.) / ES Vitoria",
    "Claro (CLARO S.A.) / GO Goiania",
    "Claro (CLARO S.A.) / MA Sao Luis",
    "Claro (CLARO S.A.) / MG Belo Horizonte",
    "Claro (CLARO S.A.) / MT Cuiaba",
    "Claro (CLARO S.A.) / PA Belem",
    "Claro (CLARO S.A.) / PB Joao Pessoa",
    "Claro (CLARO S.A.) / PE Recife",
    "Claro (CLARO S.A.) / PI Teresina",
    "Claro (CLARO S.A.) / PR Curitiba",
    "Claro (CLARO S.A.) / RJ Rio de Janeiro",
    "Claro (CLARO S.A.) / RN Natal",
    "Claro (CLARO S.A.) / RO Porto Velho",
    "Claro (CLARO S.A.) / RR Boa Vista",
    "Claro (CLARO S.A.) / RS Porto Alegre",
    "Claro (CLARO S.A.) / SC Florianopolis",
    "Claro (CLARO S.A.) / SE Aracaju",
    "Claro (CLARO S.A.) / SP Sao Paulo",
    "CTBC Cellular / MG Belo Horizonte",
    "CTBC Cellular / MS Campo Grande",
    "CTBC Cellular / SP Sao Paulo",
    "CTBC Cellular / TO Palmas",
    "Nextel (NII Holdings Inc) / BA Salvador",
    "Nextel (NII Holdings Inc) / CE Fortaleza",
    "Nextel (NII Holdings Inc) / DF Brasilia",
    "Nextel (NII Holdings Inc) / ES Vitoria",
    "Nextel (NII Holdings Inc) / GO Goiania",
    "Nextel (NII Holdings Inc) / MG Belo Horizonte",
    "Nextel (NII Holdings Inc) / PE Recife",
    "Nextel (NII Holdings Inc) / PR Curitiba",
    "Nextel (NII Holdings Inc) / RJ Rio de Janeiro",
    "Nextel (NII Holdings Inc) / RS Porto Alegre",
    "Nextel (NII Holdings Inc) / SC Florianopolis",
    "Nextel (NII Holdings Inc) / SP Sao Paulo",
    "Oi (TNL PCS S.A.) / AL Maceio",
    "Oi (TNL PCS S.A.) / AM Manaus",
    "Oi (TNL PCS S.A.) / AP Macapa",
    "Oi (TNL PCS S.A.) / BA Salvador",
    "Oi (TNL PCS S.A.) / CE Fortaleza",
    "Oi (TNL PCS S.A.) / DF Brasilia",
    "Oi (TNL PCS S.A.) / ES Vitoria",
    "Oi (TNL PCS S.A.) / MA Sao Luis",
    "Oi (TNL PCS S.A.) / MG Belo Horizonte",
    "Oi (TNL PCS S.A.) / PA Belem",
    "Oi (TNL PCS S.A.) / PB Joao Pessoa",
    "Oi (TNL PCS S.A.) / PE Recife",
    "Oi (TNL PCS S.A.) / PI Teresina",
    "Oi (TNL PCS S.A.) / PR Curitiba",
    "Oi (TNL PCS S.A.) / RJ Rio de Janeiro",
    "Oi (TNL PCS S.A.) / RN Natal",
    "Oi (TNL PCS S.A.) / RR Boa Vista",
    "Oi (TNL PCS S.A.) / SE Aracaju",
    "Oi (TNL PCS S.A.) / SP Sao Paulo",
    "Oi/Amazonia Celular / AM Manaus",
    "Oi/Amazonia Celular / AP Macapa",
    "Oi/Amazonia Celular / MA Sao Luis",
    "Oi/Amazonia Celular / PA Belem",
    "Oi/Amazonia Celular / RR Boa Vista",
    "Oi/Brasil Telecom Celular / AC Rio Branco",
    "Oi/Brasil Telecom Celular / DF Brasilia",
    "Oi/Brasil Telecom Celular / GO Goiania",
    "Oi/Brasil Telecom Celular / MS Campo Grande",
    "Oi/Brasil Telecom Celular / MT Cuiaba",
    "Oi/Brasil Telecom Celular / PR Curitiba",
    "Oi/Brasil Telecom Celular / RO Porto Velho",
    "Oi/Brasil Telecom Celular / RS Porto Alegre",
    "Oi/Brasil Telecom Celular / SC Florianopolis",
    "Oi/Brasil Telecom Celular / TO Palmas",
    "Sercomtel Celular / PR Curitiba",
    "TIM Brasil / AC Rio Branco",
    "TIM Brasil / AL Maceio",
    "TIM Brasil / AM Manaus",
    "TIM Brasil / AP Macapa",
    "TIM Brasil / BA Salvador",
    "TIM Brasil / CE Fortaleza",
    "TIM Brasil / DF Brasilia",
    "TIM Brasil / ES Vitoria",
    "TIM Brasil / GO Goiania",
    "TIM Brasil / MA Sao Luis",
    "TIM Brasil / MG Belo Horizonte",
    "TIM Brasil / MS Campo Grande",
    "TIM Brasil / MT Cuiaba",
    "TIM Brasil / PA Belem",
    "TIM Brasil / PB Joao Pessoa",
    "TIM Brasil / PE Recife",
    "TIM Brasil / PI Teresina",
    "TIM Brasil / PR Curitiba",
    "TIM Brasil / RJ Rio de Janeiro",
    "TIM Brasil / RN Natal",
    "TIM Brasil / RO Porto Velho",
    "TIM Brasil / RR Boa Vista",
    "TIM Brasil / RS Porto Alegre",
    "TIM Brasil / SC Florianopolis",
    "TIM Brasil / SE Aracaju",
    "TIM Brasil / SP Sao Paulo",
    "TIM Brasil / TO Palmas",
    "Vivo / AC Rio Branco",
    "Vivo / AL Maceio",
    "Vivo / AM Manaus",
    "Vivo / AP Macapa",
    "Vivo / BA Salvador",
    "Vivo / CE Fortaleza",
    "Vivo / DF Brasilia",
    "Vivo / ES Vitoria",
    "Vivo / GO Goiania",
    "Vivo / MA Sao Luis",
    "Vivo / MG Belo Horizonte (fka Telemig Celular)",
    "Vivo / MS Campo Grande",
    "Vivo / MT Cuiaba",
    "Vivo / PA Belem",
    "Vivo / PB Joao Pessoa",
    "Vivo / PE Pernambuco",
    "Vivo / PE Recife",
    "Vivo / PI Teresina",
    "Vivo / PR Curitiba",
    "Vivo / RJ Rio de Janeiro",
    "Vivo / RN Natal",
    "Vivo / RO Porto Velho",
    "Vivo / RR Boa Vista",
    "Vivo / RS Porto Alegre",
    "Vivo / SC Florianopolis",
    "Vivo / SE Aracaju",
    "Vivo / SP Sao Paulo",
    "Vivo / TO Palmas");

country["Brunéi Darussalam"] = new Array("b-mobile (B-Mobile Communications Sdn Bhd)",
    "DTSCom (DataStream Technology)");
country["Bulgarie"] = new Array("GLOBUL (Cosmo Bulgaria Mobile EAD)",
    "M-Tel BG (Mobiltel EAD)",
    "vivacom (BTC - Bulgarian Telecommunications Company AD)");
country["Burkina Faso"] = new Array("Airtel Burkina Faso (fka Zain)",
    "Onatel",
    "Telecel Faso");
country["Burundi"] = new Array("Africell (Africell PLC Company)",
    "ONATEL",
    "Spacetel (Econet Wireless Burundi)",
    "U-COM Burundi (fka Telecel)");
country["Cambodge"] = new Array("Beeline-KH (Sotelco Ltd)",
    "CADCOMMS (Cambodia Advance Communications Co. Ltd)",
    "Excell (CDMA)",
    "Hello Axiata Company Ltd",
    "Metfone (Viettel)",
    "Mfone",
    "MOBITEL (CamGSM)",
    "S Telecom (CDMA)",
    "SMART MOBILE (Latelz Co. Ltd)",
    "Star-Cell (Applifone Co. Ltd)");
country["Cameroun"] = new Array("MTN Cameroon",
    "Orange");
country["Canada"] = new Array("Bell Aliant (CDMA)",
    "Bell Mobility",
    "Fido Solutions (Rogers Communications Inc)",
    "FIRST Networks Operations",
    "Moblicity (DAVE Wireless)",
    "Rogers Wireless (Rogers Communications Inc)",
    "SaskTel Mobility (CDMA)",
    "TBayTel (Thunder Bay Telephone Mobility) (CDMA)",
    "TELUS Mobility (CDMA)",
    "Videotron",
    "WIND Mobile (Globalive Communications)");
country["Cap-Vert"] = new Array("CVMovel", "T%2B TELECOMUNICACOES");
country["Chili"] = new Array("Claro Chile",
    "Entel PCS",
    "Movistar (Telefonica Movil de Chile)");
country["Chine"] = new Array("China Mobile",
    "China Telecom (CDMA)",
    "China Unicom");
country["Chypre"] = new Array("Cytamobile-Vodafone",
    "MTN Cyprus (fka Areeba)",
    "PrimeTel PLC");
country["Colombie"] = new Array("COMCEL (Comunicacion Celular S.A.)",
    "Movistar (Telefonica Moviles Colombia S.A.)",
    "Tigo (Colombia Movil S.A.)");
country["Communauté de la Dominique"] = new Array("Cable % Wireless Dominica",
    "Digicel Dominica");
country["Comores"] = new Array("HURI (Comores Telecom)");
country["Congo"] = new Array("Airtel Congo Brazzaville (fka Zain)",
    "MTN Congo (Libertis Telecom)");
country["Costa Rica"] = new Array("I.C.E. (Instituto Costarricense de Electricidad)");
country["Cote d'Ivoire"] = new Array("KoZ (Comium Ivory Coast)",
    "Moov (Atlantique Telecom)",
    "Orange CI",
    "ORICEL");
country["Croatie"] = new Array("T-Mobile HR",
    "Tele2",
    "VIP-NET");
country["Cuba"] = new Array("ETECSA (Empresa de Telecommunicaciones de Cuba)");
country["Danemark"] = new Array("3 DK (Hi3G Denmark ApS)",
    "BiBoB (Telenor MVNO)",
    "CBB Mobil (Telenor MVNO)",
    "Comendo Telecom A/S (TDC MVNO)",
    "Communicate A/S",
    "End2End Connectivity (TDC MVNO)",
    "Lebara Mobile (Telenor MVNO)",
    "Lycamobile Denmark (TDC MVNO)",
    "Maxtel.dk ApS (TDC MVNO)",
    "Mundio Mobile",
    "Nordisk Mobiltelefon",
    "Onfone ApS (Telenor MVNO)",
    "TDC Mobil",
    "Telenor Denmark (Sonofon)",
    "Telia DK");
country["Egypte"] = new Array("Etisalat Egypt",
    "Mobinil (ECMS-Mobinil)",
    "Vodafone Egypt");
country["El Salvador"] = new Array("Claro (CTE Telecom Personal)",
    "Digicel El Salvador",
    "Telefonica Moviles El Salvador",
    "Tigo (Telemovil EL Salvador)");
country["Equateur"] = new Array("Alegro (Telecsa S.A.)",
    "Movistar (Otecel S.A.)",
    "Porta (Conecel S.A. - America Movil)");
country["Estonie"] = new Array("Elisa Eesti",
    "EMT",
    "Tele 2 Eesti");
country["Espagne"] = new Array("Barablu Movil Espana (Movistar MVNO)",
	"BT Movil Espana (Vodafone MVNO)",
    "DigiMobil (Best Telecom) (Movistar MVNO)",
    "Euskaltel (Vodafone MVNO)",
    "fonYou Telecom (Movistar MVNO)",
    "Jazztel (Orange MVNO)",
    "LycaMobile (Movistar MVNO)",
    "More Minutes Communications (Orange MVNO)",
    "Movistar (Telefonica Moviles Espana)",
    "Mundo R (Vodafone MVNO)",
    "ONO (Cableuropa, S.A.U.) (Movistar MVNO)",
    "Orange (France Telecom Espana) (fka Amena)",
    "Simyo ES (KPN/Orange MVNO)",
    "TeleCable (Vodafone MVNO)",
    "Vodafone Espana",
    "Yoigo (Xfera Moviles)");
country["États-Unis"] = new Array("Advantage Cellular Systems",
   "Airadigm Communications",
   "Alltel (CDMA)",
   "ASTAC (Arctic Slope Cellular)",
   "AT&T Mobility (fka Cingular Wireless)",
   "Bug Tussel Wireless",
   "Caprock Cellular",
   "Carolina West Wireless",
   "Cellular 29 Plus",
   "Cellular One",
   "Cellular South",
   "Choice Wireless Lc",
   "Cincinnati Bell",
   "Coleman County Telecom",
   "Commnet Wireless",
   "Consolidated Telecom",
   "Corr Wireless",
   "Cricket Communications (CDMA)",
   "Epic Touch (Elkhart Telephone Co.)",
   "Globalstar USA (Satellite)",
   "GTA Wireless",
   "i wireless",
   "Illinois Valley Cellular",
   "Indigo Wireless",
   "Iris Wireless LLC",
   "Keystone Wireless (aka Immix Wireless)",
   "Long Lines Wireless",
   "Metro PCS",
   "Mid-Rivers Wireless (CDMA)",
   "Mid-Tex Cellular (CDMA)",
   "Mohave Cellular",
   "North Dakota Network",
   "Northstar Technology",
   "NTELOS Communications",
   "Oklahoma Western",
   "PACE (Kaplan Telephone Company)",
   "Panhandle Telecommunications Systems",
   "PinPoint Wireless",
   "Pioneer Cellular",
   "Plateau Wireless",
   "Simmetry (TMP Corporation)",
   "Southern Communications Services (iDEN)",
   "Sprint Nextel (CDMA / iDEN)",
   "T-Mobile USA",
   "Thumb Cellular",
   "U.S. Cellular (CDMA)",
   "Union Telephone Company",
   "United Wireless",
   "Verizon Wireless (CDMA)",
   "Viaero Wireless",
   "West Central Wireless",
   "Wilkes Cellular",
   "Wireless Communications Venture",
   "XIT Communications");
country["Ethiopie"] = new Array("ETMTN (Ethiopian Telecommunications Corporatio)");
country["Émirats arabes unis"] = new Array("du (Emirates Integrated Telecommunications Company)",
   "Etisalat (Emirates Telecom Corp)");
country["Fédération de Russie"] = new Array("AKOS (Rostelecom)",
    "Altaysvyaz (ETK)",
    "Arkhangelsk Mobile Network (Tele2)",
    "Astrakhan GSM-900 (SMARTS)",
    "Baykalwestcom",
    "Belgorodskaya Cellular Communications (Tele2)",
    "Cellular Communications of Adegeya (Tele2)",
    "Chelyabinskaya Cellular Communications (Tele2)",
    "Ekaterinburg 2000 (MOTIV)",
    "EniseyTeleCom",
    "Kemerovskaya Mobile Communication (Tele2)",
    "Kodotel (SPS)",
    "Kurskaya Cellular Communications (Tele2)",
    "Kuzbass Cellular Phone GSM (ETK)",
    "Lipetsk Mobail (Tele2)",
    "MegaFON open Joint Stock Company",
    "Megafon Redirect",
    "Mobile TeleSystems",
    "MTS - DagTelecom",
    "MTS - Mobile Communications Systems",
    "MTS - Sibintertelecom",
    "Murmansk Mobile Network (Tele2)",
    "New Telephone Company",
    "Nizhegorodskaya Cellular Communications",
    "Novgorod Communications (Tele2)",
    "Orenburg-GSM (SMARTS)",
    "Parma Mobile (Tele2)",
    "Penza - GSM (SMARTS)",
    "Personnal Communicational Regional Systems (Tele2)",
    "Rostelecom",
    "Rostov Cellular Com. (Tele2)",
    "RP Technologies (Tele2)",
    "Sakhalin Telecom Mobile (Beeline)",
    "Sankt Petersburg Telecom (Tele2)",
    "Shupashkar - GSM (SMARTS)",
    "Siberian Cellular Communications (Tele2)",
    "SMARTS",
    "Smolensk Mobile Networks (Tele2)",
    "Telecom-Evrazia (Tele2)",
    "Teleset LTD (Tele2)",
    "Uliyanovsk-GSM (NCC)",
    "Uralsvyazinform",
    "Vimpelcom (Beeline)",
    "Vimpelcom (Beeline) Redirect",
    "Volgograd - GSM (SMARTS)",
    "Votec Mobile (Tele2)",
    "Wireless Information Technologies (Rostelecom)",
    "Yaroslavl-GSM (SMARTS)");
country["Fidji"] = new Array("Digicel Fiji",
    "Vodafone Fiji");
country["Finlande"] = new Array("Alands Mobiltelefon AB",
    "DNA Ltd",
    "Elisa Oyj",
    "Elisa Oyj (Saunalahti)",
    "Sonera (TeliaSonera Finland Oyj)");
country["France"] = new Array("Bouygues Telecom",
    "Orange France (France Telecom)",
    "SFR");
country["Gabon"] = new Array("Airtel Gabon (fka Zain)",
    "Libertis",
    "Moov (Atlantique Telecom Gabon)",
    "USAN-Gabon");
country["Gambie"] = new Array("Africell Gambia",
    "Comium Gambia",
    "Gamcel",
    "Qcell");
country["Géorgie"] = new Array("Geocell",
    "Magti GSM (Magticom)",
    "Mobitel (Beeline)");
country["Ghana"] = new Array("Airtel Ghana (fka Zain)",
    "Kasapa Telecom Ltd (CDMA)",
    "MTN (Scancom Ghana Ltd)",
    "tiGO (Millicom Ghana)",
    "Vodafone Ghana (Ghana Telecommunications Company Ltd)");
country["Gibraltar"] = new Array("GibTel");
country["Grèce"] = new Array("Cosmote (Mobile Telecommunications S.A.)",
    "Vodafone Greece",
    "Wind (Wind Hellas Telecommunications S.A.)");
country["Grenade"] = new Array("AWS Grenada",
    "Cable & Wireless Grenada",
    "Digicel Grenada");
country["Groenland"] = new Array("TELE Greenland");
country["Guadeloupe"] = new Array("Digicel Guadeloupe (fka Bouygues Telecom Caraibe)",
    "MIO GSM (Dauphin Telecom)",
    "Orange Caraibe Mobiles",
    "Outremer Telecom",
    "Telcell (Saint Martin et Saint Barthelemy Telcell Sarl)");
country["Guam"] = new Array("DOCOMO PACIFIC Inc.",
    "GTA Wireless (Pulse Mobile LLC)");
country["Guatemala"] = new Array("Claro (TELGUA)",
    "movistar (Telefonica Moviles Guatemala)",
    "Tigo (Comcel Guatemala)");
country["Guernesey"] = new Array("Airtel Vodafone (Guernsey Airtel Ltd)",
    "Sure Mobile (Cable %26 Wireless Guernsey Ltd)");
country["Guinée"] = new Array("Cellcom Guinee",
    "MTN (Areeba Guinea)",
    "Orange Guinee",
    "Telecel (INTERCEL Guinee)");
country["Guinée-Bissau"] = new Array("MTN (Spacetel Guinee-Bissau)",
    "Orange Bissau");
country["Guinée équatoriale"] = new Array("Orange GQ (GETESA)");
country["Guyane"] = new Array("Cellink Plus (Guyana Telephone %26 Telegraph Co.)",
    "Digicel Guyana");
country["Guyane Française"] = new Array("Digicel Guyane (fka Bouygues Telecom Caraibe)",
    "Orange Caraibe Mobiles",
    "Outremer Telecom");
country["Haïti"] = new Array("Digicel Haiti (Unigestion Holding S.A.)",
    "Voila (ComCEL)");
country["Honduras"] = new Array("Claro Honduras",
    "Tigo (Telefonica Celular S.A. - Celtel)");
country["Hong Kong"] = new Array("3 (Hutchison Telecom HK Ltd)",
    "China Mobile HK (fka Peoples)",
    "China Motion Telecom (CSL MVNO)",
    "China Unicom HK Limited (3 MVNO)",
    "China-HongKong Telecom (3 MVNO)",
    "CITIC Telecom 1616 (CSL MVNO)",
    "CSL Limited",
    "PCCW-HKT Limited",
    "SmarTone-Vodafone");
country["Hongrie"] = new Array("T-Mobile Hungary (Magyar Telekom)",
    "Telenor (fka Pannon)",
    "Vodafone");
country["Iles Caïmans"] = new Array("AT&T (Wireless Ventures)",
    "Cable & Wireless (Cayman Islands)",
    "Digicel Cayman");
country["Iles Cook"] = new Array("Telecom Cook Islands");
country["Iles Falkland"] = new Array("Cable & Wireless");
country["Iles Féroé"] = new Array("Faroese Telecom GSM",
    "VODAFONE FO");
country["Iles Salomon"] = new Array("Breeze (Solomon Telekom Co Ltd)");
country["Îles Turques et Caïques"] = new Array("Cable & Wireless West Indies Ltd (Turks & Caicos)",
   "Digicel (Turks & Caicos) Ltd");
country["Îles Vierges Britanniques"] = new Array("Cable & Wireless (West Indies)",
   "Caribbean Cellular Telephone (CCT)");
country["Iles Vierges Américaines"] = new Array("AT&T Mobility (fka Cingular Wireless)",
   "Centennial Puerto Rico Operations Corp.)",
   "Sprint Spectrum");
country["Inde"] = new Array("Aircel (Dishnet Wireless Ltd) / Andhra Pradesh",
    "Aircel (Dishnet Wireless Ltd) / Assam",
    "Aircel (Dishnet Wireless Ltd) / Bihar and Jharkhand",
    "Aircel (Dishnet Wireless Ltd) / Chennai",
    "Aircel (Dishnet Wireless Ltd) / Delhi",
    "Aircel (Dishnet Wireless Ltd) / Gujarat",
    "Aircel (Dishnet Wireless Ltd) / Haryana",
    "Aircel (Dishnet Wireless Ltd) / Himachal Pradesh",
    "Aircel (Dishnet Wireless Ltd) / Karnataka",
    "Aircel (Dishnet Wireless Ltd) / Kerala",
    "Aircel (Dishnet Wireless Ltd) / Kolkata",
    "Aircel (Dishnet Wireless Ltd) / Madhya Pradesh",
    "Aircel (Dishnet Wireless Ltd) / Maharashtra",
    "Aircel (Dishnet Wireless Ltd) / Mumbai",
    "Aircel (Dishnet Wireless Ltd) / North East India",
    "Aircel (Dishnet Wireless Ltd) / Orissa",
    "Aircel (Dishnet Wireless Ltd) / Punjab",
    "Aircel (Dishnet Wireless Ltd) / Rajasthan",
    "Aircel (Dishnet Wireless Ltd) / Tamil Nadu",
    "Aircel (Dishnet Wireless Ltd) / Uttar Pradesh (East)",
    "Aircel (Dishnet Wireless Ltd) / Uttar Pradesh (West)",
    "Aircel (Dishnet Wireless Ltd) / West Bengal",
    "Airtel (Bharti Airtel Ltd) / Andhra Pradesh",
    "Airtel (Bharti Airtel Ltd) / Assam",
    "Airtel (Bharti Airtel Ltd) / Bihar and Jharkhand",
    "Airtel (Bharti Airtel Ltd) / Chennai",
    "Airtel (Bharti Airtel Ltd) / Delhi",
    "Airtel (Bharti Airtel Ltd) / Gujarat",
    "Airtel (Bharti Airtel Ltd) / Haryana",
    "Airtel (Bharti Airtel Ltd) / Himachal Pradesh",
    "Airtel (Bharti Airtel Ltd) / Karnataka",
    "Airtel (Bharti Airtel Ltd) / Kerala",
    "Airtel (Bharti Airtel Ltd) / Kolkata",
    "Airtel (Bharti Airtel Ltd) / Madhya Pradesh",
    "Airtel (Bharti Airtel Ltd) / Maharashtra",
    "Airtel (Bharti Airtel Ltd) / Mumbai",
    "Airtel (Bharti Airtel Ltd) / North East India",
    "Airtel (Bharti Airtel Ltd) / Orissa",
    "Airtel (Bharti Airtel Ltd) / Punjab",
    "Airtel (Bharti Airtel Ltd) / Rajasthan",
    "Airtel (Bharti Airtel Ltd) / Tamil Nadu",
    "Airtel (Bharti Airtel Ltd) / Uttar Pradesh (East)",
    "Airtel (Bharti Airtel Ltd) / Uttar Pradesh (West)",
    "Airtel (Bharti Airtel Ltd) / West Bengal",
    "CellOne (BSNL) / Andhra Pradesh",
    "CellOne (BSNL) / Assam",
    "CellOne (BSNL) / Bihar and Jharkhand",
    "CellOne (BSNL) / Chennai",
    "CellOne (BSNL) / Gujarat",
    "CellOne (BSNL) / Haryana",
    "CellOne (BSNL) / Himachal Pradesh",
    "CellOne (BSNL) / Jammu and Kashmir",
    "CellOne (BSNL) / Karnataka",
    "CellOne (BSNL) / Kerala",
    "CellOne (BSNL) / Kolkata",
    "CellOne (BSNL) / Madhya Pradesh",
    "CellOne (BSNL) / Maharashtra",
    "CellOne (BSNL) / North East India",
    "CellOne (BSNL) / Orissa",
    "CellOne (BSNL) / Punjab",
    "CellOne (BSNL) / Rajasthan",
    "CellOne (BSNL) / Tamil Nadu",
    "CellOne (BSNL) / Uttar Pradesh (East)",
    "CellOne (BSNL) / Uttar Pradesh (West)",
    "CellOne (BSNL) / West Bengal",
    "Dolphin/Trump (MTNL) / Delhi",
    "Dolphin/Trump (MTNL) / Mumbai",
    "Etisalat DB Telecom (fka Swan) / Delhi",
    "Etisalat DB Telecom (fka Swan) / Gujarat",
    "Etisalat DB Telecom (fka Swan) / Madhya Pradesh",
    "Etisalat DB Telecom (fka Swan) / Maharashtra",
    "Etisalat DB Telecom (fka Swan) / Mumbai",
    "Etisalat DB Telecom (fka Swan) / Punjab",
    "IDEA (IDEA Cellular Ltd) / Andhra Pradesh",
    "IDEA (IDEA Cellular Ltd) / Assam",
    "IDEA (IDEA Cellular Ltd) / Bihar and Jharkhand",
    "IDEA (IDEA Cellular Ltd) / Delhi",
    "IDEA (IDEA Cellular Ltd) / Gujarat",
    "IDEA (IDEA Cellular Ltd) / Haryana",
    "IDEA (IDEA Cellular Ltd) / Himachal Pradesh",
    "IDEA (IDEA Cellular Ltd) / Kerala",
    "IDEA (IDEA Cellular Ltd) / Kolkata",
    "IDEA (IDEA Cellular Ltd) / Madhya Pradesh",
    "IDEA (IDEA Cellular Ltd) / Maharashtra",
    "IDEA (IDEA Cellular Ltd) / Mumbai",
    "IDEA (IDEA Cellular Ltd) / North East India",
    "IDEA (IDEA Cellular Ltd) / Orissa",
    "IDEA (IDEA Cellular Ltd) / Rajasthan",
    "IDEA (IDEA Cellular Ltd) / Tamil Nadu",
    "IDEA (IDEA Cellular Ltd) / Uttar Pradesh (East)",
    "IDEA (IDEA Cellular Ltd) / Uttar Pradesh (West)",
    "IDEA (IDEA Cellular Ltd) / West Bengal",
    "IDEA (IDEA Cellular Ltd/Spice Telecom) / Karnataka",
    "IDEA (IDEA Cellular Ltd/Spice Telecom) / Punjab",
    "Loop Mobile (Loop Telecom Ltd) (fka BPL Mobile) / Mumbai",
    "MTS (Sistema Shyam) (CDMA) / Andhra Pradesh",
    "MTS (Sistema Shyam) (CDMA) / Bihar and Jharkhand",
    "MTS (Sistema Shyam) (CDMA) / Delhi",
    "MTS (Sistema Shyam) (CDMA) / Gujarat",
    "MTS (Sistema Shyam) (CDMA) / Haryana",
    "MTS (Sistema Shyam) (CDMA) / Karnataka",
    "MTS (Sistema Shyam) (CDMA) / Kerala",
    "MTS (Sistema Shyam) (CDMA) / Kolkata",
    "MTS (Sistema Shyam) (CDMA) / Maharashtra",
    "MTS (Sistema Shyam) (CDMA) / Mumbai",
    "MTS (Sistema Shyam) (CDMA) / Rajasthan",
    "MTS (Sistema Shyam) (CDMA) / Tamil Nadu",
    "MTS (Sistema Shyam) (CDMA) / Uttar Pradesh (East)",
    "MTS (Sistema Shyam) (CDMA) / Uttar Pradesh (West)",
    "MTS (Sistema Shyam) (CDMA) / West Bengal",
    "Reliance Communications Ltd (CDMA) / Andhra Pradesh",
    "Reliance Communications Ltd (CDMA) / Bihar and Jharkhand",
    "Reliance Communications Ltd (CDMA) / Chennai",
    "Reliance Communications Ltd (CDMA) / Delhi",
    "Reliance Communications Ltd (CDMA) / Gujarat",
    "Reliance Communications Ltd (CDMA) / Haryana",
    "Reliance Communications Ltd (CDMA) / Himachal Pradesh",
    "Reliance Communications Ltd (CDMA) / Karnataka",
    "Reliance Communications Ltd (CDMA) / Kerala",
    "Reliance Communications Ltd (CDMA) / Madhya Pradesh",
    "Reliance Communications Ltd (CDMA) / Maharashtra",
    "Reliance Communications Ltd (CDMA) / Mumbai",
    "Reliance Communications Ltd (CDMA) / Orissa",
    "Reliance Communications Ltd (CDMA) / Punjab",
    "Reliance Communications Ltd (CDMA) / Rajasthan",
    "Reliance Communications Ltd (CDMA) / Tamil Nadu",
    "Reliance Communications Ltd (CDMA) / Uttar Pradesh (East)",
    "Reliance Communications Ltd (CDMA) / Uttar Pradesh (West)",
    "Reliance Communications Ltd (CDMA) / West Bengal",
    "Reliance Communications Ltd / Andhra Pradesh",
    "Reliance Communications Ltd / Delhi",
    "Reliance Communications Ltd / Haryana",
    "Reliance Communications Ltd / Jammu and Kashmir",
    "Reliance Communications Ltd / Karnataka",
    "Reliance Communications Ltd / Kerala",
    "Reliance Communications Ltd / Maharashtra",
    "Reliance Communications Ltd / Mumbai",
    "Reliance Communications Ltd / Punjab",
    "Reliance Communications Ltd / Rajasthan",
    "Reliance Communications Ltd / Tamil Nadu",
    "Reliance Communications Ltd / Uttar Pradesh (East)",
    "Reliance Communications Ltd / Uttar Pradesh (West)",
    "Reliance Telecom Ltd / Bihar and Jharkhand",
    "Reliance Telecom Ltd / Himachal Pradesh",
    "Reliance Telecom Ltd / Kolkata",
    "Reliance Telecom Ltd / Madhya Pradesh",
    "Reliance Telecom Ltd / Orissa",
    "Reliance Telecom Ltd / West Bengal",
    "S Tel / Orissa",
    "TATA Docomo (TTSL) / Andhra Pradesh",
    "TATA Docomo (TTSL) / Bihar and Jharkhand",
    "TATA Docomo (TTSL) / Gujarat",
    "TATA Docomo (TTSL) / Haryana",
    "TATA Docomo (TTSL) / Himachal Pradesh",
    "TATA Docomo (TTSL) / Karnataka",
    "TATA Docomo (TTSL) / Kerala",
    "TATA Docomo (TTSL) / Kolkata",
    "TATA Docomo (TTSL) / Madhya Pradesh",
    "TATA Docomo (TTSL) / Maharashtra",
    "TATA Docomo (TTSL) / Mumbai",
    "TATA Docomo (TTSL) / Orissa",
    "TATA Docomo (TTSL) / Punjab",
    "TATA Docomo (TTSL) / Rajasthan",
    "TATA Docomo (TTSL) / Tamil Nadu",
    "TATA Docomo (TTSL) / Uttar Pradesh (East)",
    "TATA Docomo (TTSL) / Uttar Pradesh (West)",
    "TATA Docomo (TTSL) / West Bengal",
    "Videocon (fka Datacom) / Gujarat",
    "Videocon (fka Datacom) / Haryana",
    "Videocon (fka Datacom) / Kerala",
    "Videocon (fka Datacom) / Madhya Pradesh",
    "Videocon (fka Datacom) / Mumbai",
    "Videocon (fka Datacom) / Uttar Pradesh (East)",
    "Videocon (shared with HFCL Infotel Ltd) / Punjab",
    "Vodafone Essar / Andhra Pradesh",
    "Vodafone Essar / Assam",
    "Vodafone Essar / Bihar and Jharkhand",
    "Vodafone Essar / Chennai",
    "Vodafone Essar / Delhi",
    "Vodafone Essar / Gujarat",
    "Vodafone Essar / Haryana",
    "Vodafone Essar / Himachal Pradesh",
    "Vodafone Essar / Jammu and Kashmir",
    "Vodafone Essar / Karnataka",
    "Vodafone Essar / Kerala",
    "Vodafone Essar / Kolkata",
    "Vodafone Essar / Madhya Pradesh",
    "Vodafone Essar / Maharashtra",
    "Vodafone Essar / Mumbai",
    "Vodafone Essar / North East India",
    "Vodafone Essar / Orissa",
    "Vodafone Essar / Punjab",
    "Vodafone Essar / Rajasthan",
    "Vodafone Essar / Tamil Nadu",
    "Vodafone Essar / Uttar Pradesh (East)",
    "Vodafone Essar / Uttar Pradesh (West)",
    "Vodafone Essar / West Bengal");
country["Indonesie"] = new Array("3 (PT Hutchison CP Telecommunications)",
    "AXIS (PT Natrindo Telepon Seluler)",
    "INDOSAT (PT Indonesian Satellite Corporation Tbk)",
    "Telkomsel (PT Telekomunikasi Selular)",
    "XL (PT XL Axiata Tbk) (fka Excelcomindo)");
country["Iran"] = new Array("MCI (Mobile Communications Company of Iran)",
    "MTN Irancell",
    "Taliya (Rafsanjan Industrial Complex (Coop))",
    "TKC (KFZO)");
country["Irak"] = new Array("Asiacell",
    "Korek Telecom",
    "Mobitel / Moutiny",
    "zain IQ (Atheer Telecom Iraq)");
country["Irelande"] = new Array("Hutchison 3G Ireland",
    "Meteor Mobile Telecommunications",
    "O2 Communications (Ireland)",
    "Vodafone Ireland");
country["Islande"] = new Array("IceCell",
    "NOVA",
    "Siminn",
    "Viking Wireless (IMC Island)",
    "Vodafone Iceland");
country["Isle of Man"] = new Array("Cloud 9 (Wire 9 Telecom)",
    "Manx Telecom",
    "Sure Mobile (Cable %26 Wireless Isle of Man Ltd)");
country["Israël"] = new Array("Cellcom Israel",
    "Mirs (iDEN)",
    "Orange (Partner Communications Company)",
    "Palestine / Jawwal (Palestine Cellular Communications)",
    "Palestine / Wataniya Mobile",
    "Pelephone");
country["Italie"] = new Array("Fastweb (H3G MVNO)",
    "H3G Italia",
    "Noverca (TIM MVNO)",
    "TIM (Telecom Italia SpA)",
    "Vodafone Omnitel N.V.",
    "Wind Telecomunicazioni SpA");
country["Jamaïque"] = new Array("Claro Jamaica (Oceanic Digital Jamaica Ltd)",
    "Digicel Jamaica",
    "LIME (Cable %26 Wireless)");
country["Japon"] = new Array("DOCOMO (NTT DOCOMO Inc.)",
    "eMobile (EMOBILE Limited)",
    "SoftBank (SOFTBANK MOBILE Corp.)");
country["Jersey"] = new Array("Airtel Vodafone (Jersey Airtel Ltd)",
    "Jersey Telecom",
    "Marathon Telecom Ltd",
    "Sure Mobile (Cable %26 Wireless Jersey Ltd)");
country["Jordanie"] = new Array("Orange (Jordan Telecom Group)",
    "Umniah",
    "zain JO (JMTS)");
country["Kazakhstan"] = new Array("Beeline (KaR-Tel LLP)",
    "Neo (Mobile Telecom Service LLP / Tele2)");
country["Kenya"] = new Array("Airtel Kenya (fka Zain)",
    "Econet Wireless (Essar Telecom Kenya Ltd)",
    "Orange (Telkom Kenya Ltd)",
    "Safaricom");
country["Kirghizistan"] = new Array("Beeline KG (Sky Mobile LLC)",
    "MEGACOM (Alfa Telecom Joint Stock Company)",
    "O! (NurTelecom LLC)");
country["Kuweit"] = new Array("VIVA (Kuwait Telecom Company)",
    "Wataniya Telecom (National Mobile Telecommunications Co.)",
    "zain KW (Mobile Telecommunications Co.)");
country["Laos"] = new Array("LAT (Star Telecom Company Ltd (STL))",
    "Tigo (Millicom Lao)");
country["Lesotho"] = new Array("Econet Telecom Lesotho",
    "Vodacom Lesotho");
country["Lettonie"] = new Array("Bite Latvija",
    "LMT GSM (Latvijas Mobilais Telefons)",
    "Tele2",
    "Triatel (Telekom Baltija) (CDMA)");
country["Liban"] = new Array("Alfa (MIC 1)",
    "MTC-Touch (MIC 2)");
country["Libéria"] = new Array("Cellcom Telecommunications",
    "Comium Liberia",
    "Lonestar Cell");
country["Libye"] = new Array("Al Madar Al Jadid");
country["Liechtenstein"] = new Array("Alpmobile (Alpcom AG)",
    "FL GSM (Swisscom Switzerland Ltd (Liechtenstein))",
    "FL1 (Mobilkom Liechtenstein AG)",
    "Orange FL");
country["Lituanie"] = new Array("BITE GSM",
    "Omnitel",
    "TELE2");
country["Luxembourg"] = new Array("LuxGSM (P&T Luxembourg)",
    "Tango (TANGO Mobile SA)",
    "VOXmobile (Orange S.A.)");
country["Macao"] = new Array("CTM",
    "Hutchison Telecom (Macau)",
    "SmarTone (Macau)");
country["Macédoine"] = new Array("ONE (ONE Stock Company Skopje)",
    "T-Mobile Macedonia",
    "Vip MK (Vip Operator DOOEL Skopje)");
country["Madagascar"] = new Array("Airtel Madagascar (fka Zain)",
    "Orange Madagascar",
    "Telma Mobile");
country["Malawi"] = new Array("Airtel Malawi (fka Zain)",
    "TNM (Telekom Networks Malawi)");
country["Malaisie"] = new Array("Baraka Telecom Sdn Bhd (Maxis MVNO)",
    "Celcom Axiata Bhd",
    "DiGi Telecommunications",
    "Maxis Bhd",
    "Packet One Networks Sdn Bhd",
    "REDtone Marketing Sdn Bhd (Celcom MVNO)",
    "Telekom Malaysia Bhd (U Mobile MVNO)",
    "Tron (Digi MVNO)",
    "Tune Talk Sdn Bhd (Celcom MVNO)",
    "U Mobile Sdn Bhd",
    "XOX Com Sdn Bhd (Celcom MVNO)",
    "YTL Communications Sdn Bhd (Maxis MVNO)");
country["Maldives"] = new Array("Dhiraagu (Dhivehi Raajjeyge Gulhun)",
    "WMOBILE (Wataniya Telecom Maldives)");
country["Mali"] = new Array("Malitel",
    "Orange MALI");
country["Malte"] = new Array("GO Mobile (Mobisle Communications Ltd)",
    "Melita Mobile Ltd",
    "Vodafone Malta Ltd");
country["Martinique"] = new Array("Digicel Martinique (fka Bouygues Telecom Caraibe)",
    "Orange Caraibe Mobiles",
    "Outremer Telecom");
country["Mauritanie"] = new Array("Mattel",
"Mauritel Mobiles");
country["Maurice"] = new Array("Emtel",
    "Orange MRU (Cellplus Mobile Communications)");
country["Mexique"] = new Array("Iusacell",
    "movistar (Pegaso PCS)",
    "Nextel Mexico (NII Digital) (iDEN)",
    "Telcel (Radiomovil Dipsa S.A.)");
country["Moldavie"] = new Array("IDC (Interdnestrcom) (CDMA)",
    "MoldCell",
    "Orange Moldova (fka VoXtel)",
    "Unite (MoldTelecom)");
country["Monaco"] = new Array("Monaco Telecom",
    "VALA - P& Kosovo (Monaco Telecom)");
country["Mongolie"] = new Array("MobiCom",
    "Unitel");
country["Montenegro"] = new Array("m:tel CG",
    "T-Mobile (Crnogorski Telekom)",
    "Telenor");
country["Montserrat"] = new Array("Cable & Wireless West Indies Ltd (Montserrat)");
country["Maroc"] = new Array("IAM (Maroc Telecom)",
    "Medi Telecom",
    "WANA (Wana Corporate S.A.)");
country["Mozambique"] = new Array("mcel (Mocambique Celular S.A.R.L.)",
    "Vodacom Mozambique");
country["Namibie"] = new Array("Leo (Powercom (Pty) Ltd)",
    "MTC Namibia");
country["Népal"] = new Array("Ncell (Spice Nepal Private Ltd)",
    "Nepal Doorsanchar Company Ltd (Nepal Telecom)");

country["Nicaragua"] = new Array("Claro (ENITEL)",
    "movistarNI (Telefonia Celular de Nicaragua S.A.)");
country["Niger"] = new Array("Airtel Niger (fka Zain)",
    "Orange Niger",
    "Telecel Niger");
country["Nigeria"] = new Array("Airtel Nigeria (fka Zain)",
    "Etisalat (EMTS Ltd)",
    "Glo Mobile (Globacom Ltd)",
    "MTN Nigeria",
    "Multi-links Telecommunications Ltd (CDMA)",
    "Starcomms PLC (CDMA)",
    "Visafone Communications Ltd (CDMA)");
country["Norvège"] = new Array("Lycamobile Norway Ltd (NetCom AS MVNO)",
    "Mobile Norway AS",
    "NetCom AS",
    "Tele2 Norge AS (MVNO)",
    "Telenor Mobil AS");
country["Nouvelle-Calédonie"] = new Array("Mobilis (OPT New Caledonia)");
country["Nouvelle-Zélande"] = new Array("2degrees",
    "Telecom New Zealand",
    "Vodafone New Zealand");
country["Oman"] = new Array("nawras (Omani Qatari Telecommunications Company SAOC)",
    "OMAN MOBILE (Oman Telecommunications Company)");
country["Ossétie du Sud"] = new Array("OSTELECOM Close Joint Stock Company");
country["Ouganda"] = new Array("Airtel Uganda (fka Zain)",
   "MTN Uganda",
   "Orange Uganda",
   "Uganda Telecom",
   "Warid Telecom Uganda");
country["Ouzbékistan"] = new Array("Coscom (UCell)",
   "MTS Uzbekistan (FE 'Uzdunrobita' Ltd)",
   "Unitel LLC (Beeline)");
country["Pakistan"] = new Array("Mobilink",
    "Telenor Pakistan",
    "Ufone (Pak Telecom Mobile Ltd)",
    "Warid Telecom",
    "ZONG (CMPak Limited)");
country["Palau"] = new Array("Palau Mobile");
country["Panama"] = new Array("Cable %26 Wireless Panama",
    "Claro Panama",
    "Digicel Panama",
    "Movistar");
country["Papouasie-Nouvelle-Guinée"] = new Array("Bee Mobile (BMobile Ltd)",
    "Digicel PNG");
country["Paraguay"] = new Array("Claro Paraguay",
    "Personal (Nucleo S.A)",
    "Tigo (Telecel Paraguay)",
    "VOX (Hola Paraguay S.A.)");
country["Pays-Bas"] = new Array(" Tele2 Nederland B.V. (T-Mobile MVNO)",
    "Barablu Mobile (Vodafone MVNO)",
    "Elephant Talk (MVNO)",
    "KPN B.V.",
    "KPN B.V. (Telfort B.V.)",
    "Lycamobile (Vodafone MVNO)",
    "T-Mobile NL",
    "Teleena Holding B.V. (Vodafone MVNO)",
    "Vodafone Libertel N.V.");
country["Pays-Bas Antilles"] = new Array("CSC",
    "Digicel Netherlands Antilles (fka Curacao Telecom)",
    "East Caribbean Cellular",
    "Eutel",
    "PCS",
    "Radcomm",
    "Telbo",
    "Telcell N.V.",
    "UTS Wireless Curacao (Setel N.V.)",
    "Windward Island Cellular");
country["Pérou"] = new Array("Claro Peru (America Movil Peru SAC) (fka TIM)",
    "Movistar Peru (Telefonica Moviles S.A.)");
country["Philippines"] = new Array("Digitel Mobile/Sun Cellular",
    "Globe Telecom",
    "Next Mobile",
    "Smart Communications");
country["Pologne"] = new Array("CenterNet S.A.",
    "Cyfrowy POLSAT S.A. (MVNO)",
    "Orange (PTK Centertel Sp. z o.o.)",
    "Play (P4 Sp. z o.o.)",
    "Plus (Polkomtel S.A.)",
    "T-Mobile.pl (Polska Telefonia Cyfrowa Sp. z o.o.) (fka Era)");
country["Porto Rico"] = new Array("Claro GSM (Puerto Rico Telephone Company Inc)");
country["Portugal"] = new Array("Optimus (Sonaecom)",
    "TMN",
    "Vodafone Portugal");
country["Quatar"] = new Array("Qatarnet (Q-Tel)",
    "Vodafone Qatar");
country["Réunion"] = new Array("Orange Reunion",
    "Outremer Telecom",
    "SFR Reunion (Societe Reunionnaise de Radiotelephone)");
country["République centrafricaine"] = new Array("Moov (Atlantique Telecom Centrafrique)",
    "Telecel Centrafrique");
country["République de Corée"] = new Array("KT Freetel (3G)",
    "KT Freetel (CDMA)",
    "LG Telecom (3G)",
    "LG Telecom (CDMA)",
    "SK Telecom (3G)",
    "SK Telecom (CDMA)");
country["République de Djibouti"] = new Array("Evatis (Djibouti Telecom SA)");
country["République de San Marino"] = new Array("San Marino Telecom");
country["République Dominicaine"] = new Array("Claro (Compania Dominicana de Telefonos)",
    "Orange Dominicana",
    "Tricom (CDMA)",
    "Viva (Trilogy Dominicana)");
country["République démocratique de Congo"] = new Array("Airtel D.R. of Congo (fka Zain)",
    "tiGO",
    "Vodacom Congo");
country["République du Rwanda"] = new Array("MTN-RWA (MTN Rwandacell SARL)",
    "Rwandatel",
    "Tigo Rwanda");
country["République Tchèque"] = new Array("T-Mobile CZ",
    "Vodafone CZ");
country["Romanie"] = new Array("Cosmote",
    "Digi.Mobil (RCS %26 RDS)",
    "Orange Romania",
    "Vodafone Romania");
country["Royaume-Uni"] = new Array("24 Seven Communications Ltd",
   "3 (Hutchison 3G UK Ltd)",
   "BT",
   "Cable & Wireless UK",
   "Coralbridge Ltd",
   "Lleida.net Serveis Telematics Limited",
   "Lycamobile UK Limted",
   "Moonshado Inc",
   "Mundio Mobile Limited",
   "O2 (Telefonica O2 (UK) Limited)",
   "Orange (Everything Everywhere Limited)",
   "Oxygen8 Communications UK Limited",
   "Routo Telecommunications Limited",
   "Sound Advertising Ltd",
   "Swiftnet Ltd",
   "T-Mobile UK (Everything Everywhere Limited)",
   "Telephony Services Limited",
   "Truphone (Software Cellular Network Ltd)",
   "UK Landline",
   "UK Personal Numbers Networks",
   "Vodafone Ltd");
country["Saint-Kitts-et-Nevis"] = new Array("Digicel (St. Kitts and Nevis)",
   "LIME (Cable & Wireless)",
   "UTS CariGlobe");
country["Saint-Vincent et les Grenadines"] = new Array("AT&T (St. Vincent and the Grenadines)",
   "Cable & Wireless Caribbean Cellular (St. Vincent and the Grenadines) Ltd",
   "Digicel (St. Vincent and the Grenadines) Ltd");
country["Sainte-Lucie"] = new Array("AT&T (St. Lucia)",
   "Cable & Wireless Caribbean Cellular (St Lucia) Ltd",
   "Digicel (St. Lucia) Ltd");
country["Samoa"] = new Array("Digicel Samoa");
country["Samoa Americaines"] = new Array("BlueSky Communications");
country["Sao Tomé et Principe"] = new Array("CSTmovel (Companhia Santomense de Telecomunicacoes SARL)");
country["Sénégal"] = new Array("Orange Senegal (Sonatel)",
    "Tigo (Millicom) (fka Sentel GSM)");
country["Serbie"] = new Array("Telekom Srbija",
    "Telenor",
    "VIP");
country["Seychelles"] = new Array("Airtel (Telecom Seychelles)",
    "Cable %26 Wireless (Seychelles)");
country["Sierra Leone"] = new Array("Africell (LINTEL Ltd)",
    "Airtel Sierra Leone (fka Zain)",
    "Comium",
    "Tigo Sierra Leone");
country["Singapour"] = new Array("M1 (M1 Limited)",
    "SingTel (Singapore Telecom Mobile)",
    "StarHub Mobile");
country["Slovaquie"] = new Array("Orange Slovensko",
    "T-Mobile SK (Slovak Telekom)",
    "Telefonica O2 Slovakia");
country["Slovénie"] = new Array("Mobitel",
    "Si.mobil",
    "T-2",
    "Tusmobil");
country["Somalie"] = new Array("Golis",
    "Nationlink",
    "Somafone");
country["Soudan"] = new Array("MTN Sudan",
   "Vivacell (Network of The World)",
   "Zain SD");
country["Sri Lanka"] = new Array("Bharti Airtel Lanka",
	"Dialog Axiata",
	"Etisalat Lanka",
	"Hutchison Telecommunications Lanka",
	"Mobitel");
country["Suède"] = new Array("3 (Hi3G Access AB)",
   "42 Telecom AB",
   "ACN Communications",
   "Animatele Inc.",
   "Beepsend AB",
   "Bixia AB",
   "Campuz Mobile AB",
   "Cell Mobile AB",
   "Compatel Ltd.",
   "CoolTEL ApS",
   "Devicom AB",
   "Digitel Mobile Srl",
   "Djuice Mobile Sweden",
   "EasyTelecom i Stockholm AB",
   "EuTel AB",
   "First New Media Scan",
   "Freshbody Sweden",
   "Generic Mobile Systems",
   "Glocalnet Scandinavia AB",
   "Gotalandsnatet AB",
   "iMEZ AB (Wireless Maingate AB)",
   "Infobip Ltd.",
   "Internet Payment Exchange AB",
   "IP-Only Telecommunication AB",
   "Lindholmen Science Park",
   "Ludo Mobil AB",
   "Lycamobile Sweden Ltd",
   "Megaphone AB",
   "Mercury International Carrier Services",
   "Mobil2 Sverige AB",
   "Mundio Mobile (Sweden)",
   "MyIndian AB",
   "Netett Sverige AB",
   "Netnet AS",
   "NextGen Mobile Ltd",
   "Optimal Telecom Sverige",
   "Phonera Foretag AB",
   "RebTel Networks AB",
   "Redphone AB",
   "RTC Factory AB",
   "Spinbox AB",
   "Spring Mobil AB",
   "Svea Billing Systems",
   "Svensk Konsumentmobil AB",
   "Svenska Tele i Lidkoping AB",
   "TDC Sverige AB",
   "TelaVox AB",
   "Tele2 Sverige AB (Comviq)",
   "Telecom3 Sverige AB",
   "Teledigit Scand. AB",
   "Telenor Connexion AB",
   "Telenor Sverige AB (fka Vodafone)",
   "TeliaSonera Mobile Networks AB",
   "Telogic A/S",
   "Tigo LTD",
   "Timepiece-Servicos De Consultoria Lda",
   "Truphone Ltd.",
   "Unicorn Telecom AB",
   "Ventelo Sverige AB",
   "Weblink IP Phone AB");
country["Suisse"] = new Array("IN&Phone",
   "Orange",
   "Sunrise",
   "Swisscom");
country["Suriname"] = new Array("Digicel Suriname",
   "Telesur");
country["Swaziland"] = new Array("Swazi MTN");
country["Syrie"] = new Array("MTN Syria",
   "Syriatel");
country["Tadjikistan"] = new Array("Babilon-M",
   "Beeline TJ (Tacom LLC)",
   "Indigo Tajikistan",
   "JV Somoncom",
   "TT Mobile (MLT)");
country["Taiwan"] = new Array("Chunghwa Telecom",
   "Far EasTone",
   "KG Telecom (Far EasTone MVNO)",
   "Mobitai (Taiwan Mobile MVNO)",
   "Taiwan Mobile",
   "TransAsia (Taiwan Mobile MVNO)",
   "VIBO Telecom");
country["Tanzanie"] = new Array("Airtel Tanzania (fka Zain)",
   "tiGO (MIC Tanzania Ltd)",
   "Vodacom",
   "Zantel (Zanzibar Telecom Ltd)");
country["Tchad"] = new Array("Airtel Chad (fka Zain)",
    "MILLICOM TCHAD");
country["Territoire palestinien"] = new Array("Jawwal (Palestine Cellular Communications)");
country["Thaïlande"] = new Array("AIS GSM (Advanced Info Service PLC)",
   "CAT CDMA (CAT Telecom) (CDMA)",
   "DTAC (Total Access Communications Co)",
   "GSM 1800 (Digital Phone Co Ltd (AIS))",
   "Hutch (CAT Telecom) (CDMA)",
   "TOT Mobile (Telephone Organization of Thailand)",
   "True Move");
country["Togo"] = new Array("Moov Togo (Atlantique Telecom)",
   "Togo Cell (Togo Telecom)");
country["Tonga"] = new Array("Digicel Tonga",
   "U-Call (Tonga Communications Corporation)");
country["Trinidad and Tobago"] = new Array("bmobile (TSTT)",
   "Digicel Trinidad and Tobago Ltd");
country["Tunisie"] = new Array("Orange Tunisie",
   "Tunisiana (Orascom Telecom Tunisie)",
   "TunTel (Tunisie Telecom)");
country["Turquie"] = new Array("AVEA (fka Aria and Aycell)",
   "Turkcell",
   "Vodafone Turkey (fka Telsim)");
country["Turkménistan"] = new Array("MTS Turkmenistan (Barash Communication Technologies INC)");
country["Ukraine"] = new Array("Beeline UA (Ukrainian Radio Systems) (fka WellCOM)",
   "Golden Telecom",
   "Kyivstar GSM",
   "life:) (Astelit)",
   "MTS Ukraine (fka UMC)",
   "Utel (Ukrtelecom) (UMTS)");
country["Uruguay"] = new Array("Antel (Ancel)",
   "Claro (AM Wireless Uruguay S.A.) (fka CTI Movil)",
   "Movistar (Telefonica Moviles Del Uruguay S.A.)");
country["Vanuatu"] = new Array("SMILE (Telecom Vanuatu)",
   "Digicel Vanuatu");
country["Venezuela"] = new Array("Digitel GSM",
   "Telcel C.A. (Movistar)",
   "Telecomunicaciones Movilnet",
   "Telecomunicaciones Movilnet (CDMA)");
country["Vietnam"] = new Array("Beeline VN (GTEL Mobile)",
   "MobiFone (Vietnam Mobile Telecom Services Company)",
   "Vietnamobile (Hanoi Telecom)",
   "Viettel Mobile (Vietel Corporation)",
   "Vinaphone (GPC) (Vietnam Telecom Services Company)");
country["Yemen"] = new Array("HiTS-UNITEL (Y)",
   "MTN (Spacetel)",
   "Sabafon (Yemen Company for Mobile Telephony)",
   "Yemen Mobile (CDMA)");
country["Zambie"] = new Array("Airtel Zambia (fka Zain)",
   "MTN Zambia (fka Telecel)",
   "Zambia Telecommunications Company (Zamtel)");
country["Zimbabwe"] = new Array("Econet Wireless",
   "NetOne Cellular",
   "Telecel Zimbabwe");