from django.utils.translation import ugettext_lazy as _

PHONE_COUNTRY_CODE = (
    ('', _('Select') ),
    (('+93'), _('Afghanistan')),
    (('+355'), _('Albania')),
    (('+213'), _('Algeria')),
    (('+1684'), _('American Samoa')),
    (('+376'), _('Andorra')),
    (('+244'), _('Angola')),
    (('+1264'), _('Anguilla')),
    (('+672'), _('Antarctica')),
    (('+1268'), _('Antigua and Barbuda')),
    (('+54'), _('Argentina')),
    (('+374'), _('Armenia')),
    (('+297'), _('Aruba')),
    (('+61'), _('Australia')),
    (('+43'), _('Austria')),
    (('+994'), _('Azerbaijan')),
    (('+1242'), _('Bahamas')),
    (('+973'), _('Bahrain')),
    (('+880'), _('Bangladesh')),
    (('+1246'), _('Barbados')),
    (('+375'), _('Belarus')),
    (('+32'), _('Belgium')),
    (('+501'), _('Belize')),
    (('+229'), _('Benin')),
    (('+1441'), _('Bermuda')),
    (('+975'), _('Bhutan')),
    (('+591'), _('Bolivia')),
    (('+387'), _('Bosnia and Herzegovina')),
    (('+267'), _('Botswana')),
    (('+55'), _('Brazil')),
    (('+673'), _('Brunei')),
    (('+359'), _('Bulgaria')),
    (('+226'), _('Burkina Faso')),
    (('+257'), _('Burundi')),
    (('+855'), _('Cambodia')),
    (('+237'), _('Cameroon')),
    (('+1'), _('Canada')),
    (('+238'), _('Cape Verde')),
    (('+1345'), _('Cayman Islands')),
    (('+236'), _('Central African Republic')),
    (('+235'), _('Chad')),
    (('+56'), _('Chile')),
    (('+86'), _('China')),
    (('+57'), _('Colombia')),
    (('+269'), _('Comoros')),
    (('+242'), _('Congo')),
    (('+243'), _('Congo, The Democratic Republic of the')),
    (('+682'), _('Cook Islands')),
    (('+506'), _('Costa Rica')),
    (('+225'), _('Cote D\'Ivoire')),
    (('+385'), _('Croatia')),
    (('+53'), _('Cuba')),
    (('+357'), _('Cyprus')),
    (('+420'), _('Czech Republic')),
    (('+45'), _('Denmark')),
    (('+253'), _('Djibouti')),
    (('+1767'), _('Dominica')),
    (('+18'), _('Dominican Republic')),
    (('+593'), _('Ecuador')),
    (('+20'), _('Egypt')),
    (('+503'), _('El Salvador')),
    (('+240'), _('Equatorial Guinea')),
    (('+291'), _('Eritrea')),
    (('+372'), _('Estonia')),
    (('+251'), _('Ethiopia')),
    (('+500'), _('Falkland Islands (Malvinas)')),
    (('+298'), _('Faroe Islands')),
    (('+679'), _('Fiji')),
    (('+358'), _('Finland')),
    (('+33'), _('France')),
    (('+594'), _('French Guiana')),
    (('+689'), _('French Polynesia')),
    (('+241'), _('Gabon')),
    (('+220'), _('Gambia')),
    (('+995'), _('Georgia')),
    (('+49'), _('Germany')),
    (('+233'), _('Ghana')),
    (('+350'), _('Gibraltar')),
    (('+30'), _('Greece')),
    (('+299'), _('Greenland')),
    (('+1473'), _('Grenada')),
    (('+590'), _('Guadeloupe')),
    (('+1671'), _('Guam')),
    (('+502'), _('Guatemala')),
    (('+224'), _('Guinea')),
    (('+245'), _('Guinea-Bissau')),
    (('+592'), _('Guyana')),
    (('+509'), _('Haiti')),
    (('+504'), _('Honduras')),
    (('+852'), _('Hong Kong S.A.R., China')),
    (('+36'), _('Hungary')),
    (('+354'), _('Iceland')),
    (('+91'), _('India')),
    (('+62'), _('Indonesia')),
    (('+98'), _('Iran')),
    (('+964'), _('Iraq')),
    (('+353'), _('Ireland')),
    (('+972'), _('Israel')),
    (('+39'), _('Italy')),
    (('+1876'), _('Jamaica')),
    (('+81'), _('Japan')),
    (('+962'), _('Jordan')),
    (('+7'), _('Kazakhstan')),
    (('+254'), _('Kenya')),
    (('+686'), _('Kiribati')),
    (('+850'), _('Korea, North')),
    (('+82'), _('Korea, South')),
    (('+965'), _('Kuwait')),
    (('+996'), _('Kyrgyzstan')),
    (('+856'), _('Laos')),
    (('+371'), _('Latvia')),
    (('+961'), _('Lebanon')),
    (('+266'), _('Lesotho')),
    (('+231'), _('Liberia')),
    (('+218'), _('Libya')),
    (('+423'), _('Liechtenstein')),
    (('+370'), _('Lithuania')),
    (('+352'), _('Luxembourg')),
    (('+853'), _('Macao')),
    (('+389'), _('Macedonia')),
    (('+261'), _('Madagascar')),
    (('+265'), _('Malawi')),
    (('+60'), _('Malaysia')),
    (('+960'), _('Maldives')),
    (('+223'), _('Mali')),
    (('+356'), _('Malta')),
    (('+692'), _('Marshall Islands')),
    (('+596'), _('Martinique')),
    (('+222'), _('Mauritania')),
    (('+230'), _('Mauritius')),
    (('+269'), _('Mayotte')),
    (('+52'), _('Mexico')),
    (('+691'), _('Micronesia, Federated States Of')),
    (('+373'), _('Moldova')),
    (('+377'), _('Monaco')),
    (('+976'), _('Mongolia')),
    (('+382'), _('Montenegro')),
    (('+1664'), _('Montserrat')),
    (('+212'), _('Morocco')),
    (('+258'), _('Mozambique')),
    (('+95'), _('Myanmar')),
    (('+264'), _('Namibia')),
    (('+674'), _('Nauru')),
    (('+977'), _('Nepal')),
    (('+31'), _('Netherlands')),
    (('+599'), _('Netherlands Antilles')),
    (('+687'), _('New Caledonia')),
    (('+64'), _('New Zealand')),
    (('+505'), _('Nicaragua')),
    (('+227'), _('Niger')),
    (('+234'), _('Nigeria')),
    (('+683'), _('Niue')),
    (('+1670'), _('Northern Mariana Islands')),
    (('+47'), _('Norway')),
    (('+968'), _('Oman')),
    (('+92'), _('Pakistan')),
    (('+680'), _('Palau')),
    (('+507'), _('Panama')),
    (('+675'), _('Papua New Guinea')),
    (('+595'), _('Paraguay')),
    (('+51'), _('Peru')),
    (('+63'), _('Philippines')),
    (('+48'), _('Poland')),
    (('+351'), _('Portugal')),
    (('+1787'), _('Puerto Rico')),
    (('+974'), _('Qatar')),
    (('+262'), _('Reunion')),
    (('+40'), _('Romania')),
    (('+7'), _('Russia')),
    (('+250'), _('Rwanda')),
    (('+290'), _('Saint Helena')),
    (('+1869'), _('Saint Kitts and Nevis')),
    (('+1758'), _('Saint Lucia')),
    (('+508'), _('Saint Pierre and Miquelon')),
    (('+1784'), _('Saint Vincent and the Grenadines')),
    (('+685'), _('Samoa')),
    (('+378'), _('San Marino')),
    (('+239'), _('Sao Tome and Principe')),
    (('+966'), _('Saudi Arabia')),
    (('+221'), _('Senegal')),
    (('+381'), _('Serbia')),
    (('+248'), _('Seychelles')),
    (('+232'), _('Sierra Leone')),
    (('+65'), _('Singapore')),
    (('+421'), _('Slovakia')),
    (('+386'), _('Slovenia')),
    (('+677'), _('Solomon Islands')),
    (('+252'), _('Somalia')),
    (('+27'), _('South Africa')),
    (('+34'), _('Spain')),
    (('+94'), _('Sri Lanka')),
    (('+249'), _('Sudan')),
    (('+597'), _('Suriname')),
    (('+268'), _('Swaziland')),
    (('+46'), _('Sweden')),
    (('+41'), _('Switzerland')),
    (('+963'), _('Syria')),
    (('+886'), _('Taiwan')),
    (('+992'), _('Tajikistan')),
    (('+255'), _('Tanzania')),
    (('+66'), _('Thailand')),
    (('+670'), _('Timor-Leste')),
    (('+228'), _('Togo')),
    (('+690'), _('Tokelau')),
    (('+676'), _('Tonga')),
    (('+1868'), _('Trinidad and Tobago')),
    (('+216'), _('Tunisia')),
    (('+90'), _('Turkey')),
    (('+993'), _('Turkmenistan')),
    (('+1649'), _('Turks and Caicos Islands')),
    (('+688'), _('Tuvalu')),
    (('+256'), _('Uganda')),
    (('+380'), _('Ukraine')),
    (('+971'), _('United Arab Emirates')),
    (('+44'), _('United Kingdom')),
    (('+1'), _('United States')),
    (('+598'), _('Uruguay')),
    (('+998'), _('Uzbekistan')),
    (('+678'), _('Vanuatu')),
    (('+3'), _('Vatican City State (Holy See)')),
    (('+58'), _('Venezuela')),
    (('+84'), _('Vietnam')),
    (('+1284'), _('Virgin Islands, British')),
    (('+1340'), _('Virgin Islands, US')),
    (('+681'), _('Wallis and Futuna')),
    (('+967'), _('Yemen')),
    (('+260'), _('Zambia')),
    (('+263'), _('Zimbabwe')),
    )