var countryList = [
            // Africa
            "Afrique du Sud",
            "Algérie",
            "Angola",
            "Bénin",
            "Botswana",
            "Burkina",
            "Burundi",
            "Cameroun",
            "Cap-Vert",
            "République Centrafricaine",
            "Tchad",
            "Comores",
            "Congo",
            "Djibouti",
            "Egypte",
            "Guinée Equatoriale",
            "Erythée",
            "Ethiopia",
            "Gabon",
            "Gambia",
            "Ghana",
            "Guinée",
            "Guinée-Bissau",
            "Côte-d'Ivoire",
            "Kenya",
            "Lesotho",
            "Liberia",
            "Libye",
            "Madagascar",
            "Malawi",
            "Mali",
            "Mauritanie",
            "Maurice",
            "Maroc",
            "Mozambique",
            "Namibie",
            "Niger",
            "Nigeria",
            "Rwanda",
            "Sao Tomé et Principe",
            "Sénégal",
            "Seychelles",
            "Sierra Leone",
            "Somalie",

            "Soudan",
            "Swaziland",
            "Tanzanie",
            "Togo",
            "Tunisie",
            "Ouganda",
            "Zambie",
            "Zimbabwe",
            // Asia
            "Afghanistan",
            "Bahrein",
            "Bangladesh",
            "Bhoutan",
            "Brunei",
            "Burmanie (Myanmar)",
            "Cambodge",
            "Chine",
            "Timor-Oriental",
            "Inde",
            "Indonésie",
            "Iran",
            "Irak",
            "Israël",
            "Japon",
            "Jordan",
            "Kazakhstan",
            "Corée du Nord",
            "Corée du Sud",
            "Koweït",
            "Kirghizstan",
            "Laos",
            "Liban",
            "Malaysie",
            "Maldives",
            "Mongolie",
            "Népal",
            "Oman",
            "Pakistan",
            "Philippines",
            "Qatar",
            "Fédération de Russie",
            "Arabie Saoutite",
            "Singapour",
            "Sri Lanka",
            "Syrie",
            "Tadjikistan",
            "Thaïlande",
            "Turquie",
            "Turkménistan",
            "Arabes Unis",
            "Emirats",
            "Ouzbékistan",
            "Vietnam",
            "Yémen",
            // Europe
            "Albanie",
            "Andorre",
            "Arménie",
            "Austriche",
            "Azerbaïdjan",
            "Belarus",
            "Belgique",
            "Bosnie et Herzégovine",
            "Bulgarie",
            "Croatie",
            "Chypre",
            "République Tchèque",
            "Danemark",
            "Estonie",
            "Finlande",
            "France",
            "Géorgie",
            "Allemagne",
            "Grèce",
            "Hongrie",
            "Islande",
            "Irlande",
            "Italie",
            "Lettonie",
            "Liechtenstein",
            "Lituanie",
            "Luxembourg",
            "Macédonie",
            "Malte",
            "Moldovie",
            "Monaco",
            "Monténégro",
            "Pays-Bas",
            "Norvège",
            "Pologne",
            "Portugal",
            "Romanie",
            "San Marino",
            "Serbie",
            "Slovaquie",
            "Slovénie",
            "Espagne",
            "Suède",
            "Suisse",
            "Ukraine",
            "Royaume-Uni",
            "Cité du Vatican",
            // North America
            "Antigua et Barbuda",
            "Bahamas",
            "Barbade",
            "Belize",
            "Canada",
            "Costa Rica",
            "Cuba",
            "Dominique",
            "République Dominicaine",
            "Salvador",
            "Grenade",
            "Guatemala",
            "Haïti",
            "Honduras",
            "Jamaïque",
            "Mexico",
            "Nicaragua",
            "Panama",
            "St. Kitts & Nevis",
            "St. Lucie",
            "St. Vincent & les Grenadines",
            "Trinidad & Tobago",
            "Etats-Unis",
            // Oceania
            "Australie",
            "Fidji",
            "Kiribati",
            "Iles Marshall",
            "Micronésie",
            "Nauru",
            "Nouvelle-Zélande",
            "Palau",
            "Papouasie Nouvelle-Guinée",
            "Samoa",
            "Iles Salomon",
            "Tonga",
            "Tuvalu",
            "Vanuatu",
            // South America
            "Argentine",
            "Bolivie",
            "Brésil",
            "Chili",
            "Colombie",
            "Equateur",
            "Guyane",
            "Paraguay",
            "Pérou",
            "Suriname",
            "Uruguay",
            "Venezuela"
        ];